language: node_js

node_js:
  - 16

services:
  - docker

install:
  - echo "nothing needs to be installed"

script:
  - docker build -t reverseproxy udagram-reverseproxy
  - docker build -t udagram-frontend udagram-frontend
  - docker build -t udagram-api-feed udagram-api-feed
  - docker build -t udagram-api-user udagram-api-user

  - docker tag reverseproxy danthe666/reverseproxy:v2
  - docker tag udagram-frontend danthe666/udagram-frontend:v2
  - docker tag udagram-api-feed danthe666/udagram-api-feed:v2
  - docker tag udagram-api-user danthe666/udagram-api-user:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push danthe666/reverseproxy:v2
  - docker push danthe666/udagram-frontend:v2
  - docker push danthe666/udagram-api-feed:v2
  - docker push danthe666/udagram-api-user:v2
